# Generated by Django 5.1 on 2026-04-07 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(max_length=20, verbose_name='Тип бэкапа')),
                ('status', models.CharField(choices=[('started', 'Начат'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('cancelled', 'Отменен')], max_length=10, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байты)')),
                ('tables_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество таблиц')),
                ('records_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество записей')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Лог бэкапа',
                'verbose_name_plural': 'Логи бэкапов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PopularContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('course', 'Курс'), ('lesson', 'Урок'), ('user', 'Пользователь'), ('language', 'Язык программирования')], max_length=10, verbose_name='Тип контента')),
                ('content_id', models.PositiveIntegerField(verbose_name='ID контента')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('unique_views', models.PositiveIntegerField(default=0, verbose_name='Уникальные просмотры')),
                ('enrollment_count', models.PositiveIntegerField(default=0, verbose_name='Количество записей')),
                ('completion_count', models.PositiveIntegerField(default=0, verbose_name='Количество завершений')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Последний доступ')),
                ('popularity_score', models.FloatField(default=0.0, verbose_name='Рейтинг популярности')),
            ],
            options={
                'verbose_name': 'Популярный контент',
                'verbose_name_plural': 'Популярный контент',
                'ordering': ['-popularity_score'],
                'indexes': [models.Index(fields=['content_type', 'popularity_score'], name='adminpanel__content_f9435c_idx'), models.Index(fields=['last_accessed'], name='adminpanel__last_ac_fabbdc_idx')],
                'unique_together': {('content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('view_course', 'Просмотр курса'), ('enroll_course', 'Запись на курс'), ('complete_lesson', 'Завершение урока'), ('start_lesson', 'Начало урока'), ('submit_assignment', 'Сдача задания'), ('view_profile', 'Просмотр профиля'), ('update_profile', 'Обновление профиля'), ('create_course', 'Создание курса'), ('update_course', 'Обновление курса'), ('delete_course', 'Удаление курса'), ('create_lesson', 'Создание урока'), ('update_lesson', 'Обновление урока'), ('delete_lesson', 'Удаление урока'), ('chat_message', 'Сообщение в чате'), ('support_chat', 'Обращение в поддержку')], max_length=20, verbose_name='Тип действия')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Представление объекта')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог активности',
                'verbose_name_plural': 'Логи активности',
                'ordering': ['-action_time'],
                'indexes': [models.Index(fields=['user', 'action_time'], name='adminpanel__user_id_25f70d_idx'), models.Index(fields=['action_type', 'action_time'], name='adminpanel__action__7190f5_idx'), models.Index(fields=['action_time'], name='adminpanel__action__953943_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('404', 'Not Found'), ('500', 'Internal Server Error'), ('403', 'Forbidden'), ('400', 'Bad Request'), ('javascript', 'JavaScript Error'), ('python', 'Python Error'), ('database', 'Database Error'), ('other', 'Other')], max_length=20, verbose_name='Тип ошибки')),
                ('message', models.TextField(verbose_name='Сообщение об ошибке')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='Stack Trace')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP метод')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('resolved', models.BooleanField(default=False, verbose_name='Решена')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время решения')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL, verbose_name='Кто решил')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог ошибок',
                'verbose_name_plural': 'Логи ошибок',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['error_type', 'timestamp'], name='adminpanel__error_t_7b1f8f_idx'), models.Index(fields=['resolved', 'timestamp'], name='adminpanel__resolve_4a1bdf_idx'), models.Index(fields=['timestamp'], name='adminpanel__timesta_4d7763_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=10, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('module', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модуль')),
                ('function', models.CharField(blank=True, max_length=100, null=True, verbose_name='Функция')),
                ('line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер строки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('request_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID запроса')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Системный лог',
                'verbose_name_plural': 'Системные логи',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', 'timestamp'], name='adminpanel__level_e9e212_idx'), models.Index(fields=['timestamp'], name='adminpanel__timesta_d086a5_idx'), models.Index(fields=['module', 'timestamp'], name='adminpanel__module_2b838f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Ключ сессии')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='Просмотров страниц')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'last_activity'], name='adminpanel__user_id_a674f8_idx'), models.Index(fields=['session_key'], name='adminpanel__session_ec4247_idx'), models.Index(fields=['is_active', 'last_activity'], name='adminpanel__is_acti_31f080_idx')],
            },
        ),
    ]
