# Generated by Django 5.1 on 2026-05-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_chat', 'Новый чат'), ('new_chat_message', 'Новое сообщение в чате'), ('course_enrollment', 'Запись на курс'), ('course_review', 'Отзыв на курс'), ('system', 'Системное уведомление')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
