# Generated by Django 5.1 on 2026-04-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_table_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Резервные коды'),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Двухфакторная аутентификация'),
        ),
    ]
