# Generated by Django 5.1 on 2026-05-12 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_options_alter_profile_achievements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_messages', models.BooleanField(default=True, verbose_name='Уведомления из поддержки')),
                ('new_lessons', models.BooleanField(default=True, verbose_name='Новые уроки')),
                ('course_announcements', models.BooleanField(default=True, verbose_name='Объявления курсов')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='Системные уведомления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
