# Generated by Django 5.1 on 2026-05-12 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usernotifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_profile', models.BooleanField(default=False, verbose_name='Публичный профиль')),
                ('show_email', models.BooleanField(default=False, verbose_name='Показывать email')),
                ('show_progress', models.BooleanField(default=True, verbose_name='Показывать прогресс обучения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки приватности',
                'verbose_name_plural': 'Настройки приватности',
            },
        ),
    ]
