# Generated by Django 5.1 on 2026-05-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprivacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotifications',
            name='course_announcements',
        ),
        migrations.RemoveField(
            model_name='usernotifications',
            name='system_notifications',
        ),
    ]
