# Generated by Django 5.1 on 2026-05-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_usernotifications_course_announcements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_chat', 'Новый чат'), ('new_chat_message', 'Новое сообщение в чате'), ('course_enrollment', 'Запись на курс'), ('course_review', 'Отзыв на курс'), ('new_lesson', 'Новый урок'), ('system', 'Системное уведомление')], max_length=20),
        ),
    ]
