# Generated by Django 5.1 on 2026-05-12 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_notification_notification_type'),
        ('courses', '0013_course_category_course_is_published_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat_room_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.course'),
        ),
    ]
