# Generated by Django 5.1 on 2026-05-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notification_chat_room_id_notification_course'),
        ('courses', '0014_courseenrollment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.lesson'),
        ),
    ]
