# Generated by Django 5.1 on 2026-05-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notification_lesson'),
    ]

    operations = [
    ]
