# Generated by Django 5.1 on 2026-04-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessoncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='courses.lesson', verbose_name='Завершенные уроки'),
        ),
    ]
