# Generated by Django to mark existing fields as applied

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseenrollment_completed_lessons'),
    ]

    operations = [
        # This migration marks existing fields as already applied
        # Fields lesson_type and updated_at already exist in database
    ]
