# Generated by Django 5.1 on 2026-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_mark_existing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, help_text='Видео, презентация, PDF, Word и другие файлы', null=True, upload_to='lesson_attachments/', verbose_name='Прикрепленный файл'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Текстовое содержание для лекции', verbose_name='Содержание лекции'),
        ),
    ]
