# Generated by Django 5.1 on 2026-05-08 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_lesson_video_url_lesson_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('single', 'Один вариант ответа'), ('multiple', 'Несколько вариантов ответа'), ('text', 'Свободный текстовый ответ'), ('essay', 'Развернутый ответ с проверкой')], max_length=20, verbose_name='Тип вопроса')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Баллы за вопрос')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение к ответу')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.testquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набранные баллы')),
                ('max_score', models.PositiveIntegerField(verbose_name='Максимальные баллы')),
                ('percentage', models.FloatField(verbose_name='Процент выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Требует проверки')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='TestAnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('feedback', models.TextField(blank=True, verbose_name='Обратная связь')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Требует проверки')),
                ('selected_answers', models.ManyToManyField(blank=True, to='courses.testanswer', verbose_name='Выбранные варианты')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testquestion', verbose_name='Вопрос')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to='courses.testsubmission', verbose_name='Результат теста')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
