# Generated by Django 5.1 on 2026-05-08 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_lesson_type_lesson_updated_at_testquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('ruby', 'Ruby')], max_length=20, unique=True, verbose_name='Язык программирования')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включен')),
                ('compile_command', models.CharField(max_length=200, verbose_name='Команда компиляции')),
                ('run_command', models.CharField(max_length=200, verbose_name='Команда запуска')),
                ('file_extension', models.CharField(max_length=10, verbose_name='Расширение файла')),
                ('max_execution_time', models.PositiveIntegerField(default=10, verbose_name='Макс. время выполнения (сек)')),
                ('max_memory', models.PositiveIntegerField(default=512, verbose_name='Макс. память (МБ)')),
                ('allowed_libraries', models.JSONField(default=list, verbose_name='Разрешенные библиотеки')),
                ('forbidden_patterns', models.JSONField(default=list, verbose_name='Запрещенные паттерны кода')),
                ('docker_image', models.CharField(blank=True, max_length=200, verbose_name='Docker образ')),
                ('security_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('maximum', 'Максимальный')], default='high', max_length=20, verbose_name='Уровень безопасности')),
            ],
            options={
                'verbose_name': 'Конфигурация безопасности',
                'verbose_name_plural': 'Конфигурации безопасности',
            },
        ),
        migrations.CreateModel(
            name='PracticeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('requirements', models.TextField(verbose_name='Требования к решению')),
                ('programming_language', models.CharField(max_length=20, verbose_name='Язык программирования')),
                ('starter_code', models.TextField(blank=True, verbose_name='Начальный код')),
                ('solution_code', models.TextField(blank=True, verbose_name='Код решения (для проверки)')),
                ('test_cases', models.JSONField(default=dict, verbose_name='Тестовые случаи')),
                ('time_limit', models.PositiveIntegerField(default=5, verbose_name='Лимит времени (секунды)')),
                ('memory_limit', models.PositiveIntegerField(default=256, verbose_name='Лимит памяти (МБ)')),
                ('max_attempts', models.PositiveIntegerField(default=10, verbose_name='Максимум попыток')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_assignment', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Практическое задание',
                'verbose_name_plural': 'Практические задания',
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код решения')),
                ('programming_language', models.CharField(max_length=20, verbose_name='Язык программирования')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('success', 'Успешно'), ('error', 'Ошибка'), ('timeout', 'Превышен лимит времени'), ('memory', 'Превышен лимит памяти'), ('wrong', 'Неверный ответ')], default='pending', max_length=20, verbose_name='Статус')),
                ('output', models.TextField(blank=True, verbose_name='Вывод программы')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Время выполнения (сек)')),
                ('memory_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='Использовано памяти (МБ)')),
                ('test_cases_passed', models.PositiveIntegerField(default=0, verbose_name='Пройдено тестов')),
                ('total_test_cases', models.PositiveIntegerField(default=0, verbose_name='Всего тестов')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Номер попытки')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Решено верно')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.practiceassignment', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Отправка кода',
                'verbose_name_plural': 'Отправки кода',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'user', 'attempt_number')},
            },
        ),
    ]
