# Generated by Django 5.1 on 2026-05-08 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_securityconfig_lesson_lesson_type_lesson_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Комментарий преподавателя'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время проверки'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='practiceassignment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='practiceassignment',
            name='expected_output',
            field=models.TextField(blank=True, verbose_name='Ожидаемый вывод'),
        ),
        migrations.AddField(
            model_name='practiceassignment',
            name='max_grade',
            field=models.PositiveIntegerField(default=100, verbose_name='Максимальная оценка'),
        ),
        migrations.AddField(
            model_name='practiceassignment',
            name='require_manual_review',
            field=models.BooleanField(default=False, verbose_name='Требуется ручная проверка'),
        ),
        migrations.AddField(
            model_name='practiceassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('running', 'Выполняется'), ('success', 'Успешно'), ('error', 'Ошибка'), ('timeout', 'Превышен лимит времени'), ('memory', 'Превышен лимит памяти'), ('wrong', 'Неверный ответ'), ('approved', 'Принято'), ('rejected', 'Отклонено'), ('reviewed', 'Проверено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='practiceassignment',
            name='programming_language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('ruby', 'Ruby')], max_length=20, verbose_name='Язык программирования'),
        ),
    ]
