# Generated by Django 5.1 on 2026-05-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_codesubmission_feedback_codesubmission_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='programming_language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Язык программирования'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('test', 'Тест'), ('practice', 'Практическое задание')], default='lecture', max_length=20, verbose_name='Тип урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='practiceassignment',
            name='test_cases',
            field=models.JSONField(default=list, verbose_name='Тестовые случаи'),
        ),
    ]
