# Generated by Django 5.1 on 2026-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_category_course_is_published_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная запись'),
        ),
    ]
