"""
Django settings for progage project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import dj_database_url

# Загрузка переменных окружения из .env.local (если существует)
try:
    from dotenv import load_dotenv
    env_file = Path(__file__).resolve().parent.parent / '.env.local'
    if env_file.exists():
        load_dotenv(env_file)
        print("✅ Загружены переменные из .env.local")
except ImportError:
    print("⚠️ python-dotenv не установлен, используем значения по умолчанию")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-y&92ie9klnr&01t!pq#kg017f&)+78m_3#n+8r+)i0ejvie%#l')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

    # Получаем локальный IP и добавляем в ALLOWED_HOSTS
import socket
try:
    local_ip = socket.gethostbyname(socket.gethostname())
    if not local_ip.startswith('127.'):
        allowed_hosts = f'localhost,127.0.0.1,{local_ip}'
    else:
        allowed_hosts = 'localhost,127.0.0.1'
except:
    allowed_hosts = 'localhost,127.0.0.1'

ALLOWED_HOSTS = ['*']
# CSRF Trusted Origins - для всех возможных портов разработки
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:55095',
    'http://127.0.0.1:55095',
    'https://*.lhr.life',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    # 'django_recaptcha',  # Отключено
    'django_otp',
    'django_otp.plugins.otp_totp',
    'accounts',
    'courses',
    'adminpanel',
    'chat',
    'channels',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'rate_limit_middleware.GlobalRateLimitMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.BruteForceProtectionMiddleware',
    'adminpanel.middleware.LoggingMiddleware',
    'adminpanel.middleware.ExceptionLoggingMiddleware',
]

ROOT_URLCONF = 'progage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'accounts.context_processors.recaptcha_enabled',  # Отключено
            ],
        },
    },
]

WSGI_APPLICATION = 'progage.wsgi.application'

# ASGI
ASGI_APPLICATION = 'progage.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL', default='sqlite:///' + str(BASE_DIR / 'db.sqlite3')))
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

CORS_ALLOW_CREDENTIALS = True

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Для реальной отправки
EMAIL_HOST = 'smtp.gmail.com'  # Правильный SMTP сервер Gmail
EMAIL_PORT = 587  # Правильный порт для Gmail с TLS
EMAIL_HOST_USER = 'pashokbilashenko335@gmail.com'
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Пароль приложения Gmail
EMAIL_USE_TLS = True  # Включаем TLS
EMAIL_USE_SSL = False  # Отключаем SSL
EMAIL_TIMEOUT = 60  # Большой таймаут
EMAIL_USE_LOCALTIME = True  # Добавлено для SMTP
DEFAULT_FROM_EMAIL = 'pashokbilashenko335@gmail.com'

# Password reset settings
PASSWORD_RESET_TIMEOUT = 86400  # 24 часа в секундах

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration to suppress Channels INFO messages
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'level': 'WARNING',
        'handlers': ['console'],
    },
    'loggers': {
        'django.channels': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        'daphne': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}

# Two-factor authentication settings
OTP_TOTP_ISSUER = 'Progage'
OTP_TOTP_VALIDITY = 30  # seconds
OTP_TOTP_DIGITS = 6

# Silenced system checks
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']
